[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

  
[[redirects]]
  from = "/subdirectory/*"
  to = "https://master-desirably--nutty--flounder-pgsdemo-com.preview.pagescdn.com/:splat"
  status = 200
  force = true
  headers = {Host = "https://master-desirably--nutty--flounder-pgsdemo-com.preview.pagescdn.com"}
  
[[redirects]]
  from = "/subdirectory"
  to = "https://master-desirably--nutty--flounder-pgsdemo-com.preview.pagescdn.com/index.html"
  status = 200
  force = true
  headers = {Host = "https://master-desirably--nutty--flounder-pgsdemo-com.preview.pagescdn.com/"}
