[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

  
[[redirects]]
  from = "/subdirectory/*"
  to = "https://upright-petite-bird.pgsdemo.com/:splat"
  status = 200
  force = true
  headers = {Host = "https://upright-petite-bird.pgsdemo.com/"}
  
[[redirects]]
  from = "/subdirectory"
  to = "https://upright-petite-bird.pgsdemo.com/index.html"
  status = 200
  force = true
  headers = {Host = "https://upright-petite-bird.pgsdemo.com/"}
