[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"
  
[[redirects]]
  from = "/subdirectory/assets/*"
  to = "https://clemently-cautious-coyote.pgsdemo.com/subdirectory/assets/:splat"
  status = 200
  force = true
  headers = {Host = "https://clemently-cautious-coyote.pgsdemo.com/"}
  
[[redirects]]
  from = "/subdirectory/*"
  to = "https://clemently-cautious-coyote.pgsdemo.com/:splat"
  status = 200
  force = true
  headers = {Host = "https://clemently-cautious-coyote.pgsdemo.com/"}
  
[[redirects]]
  from = "/subdirectory"
  to = "https://clemently-cautious-coyote.pgsdemo.com/index.html"
  status = 200
  force = true
  headers = {Host = "https://clemently-cautious-coyote.pgsdemo.com/"}
