[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

  
[[redirects]]
  from = "/locations/*"
  to = "https://locations-starter-reverse-proxytest.pgsdemo.com/:splat"
  status = 200
  force = true
  headers = {Host = "https://locations-starter-reverse-proxytest.pgsdemo.com"}
  
[[redirects]]
  from = "/locations"
  to = "https://locations-starter-reverse-proxytest.pgsdemo.com/index.html"
  status = 200
  force = true
  headers = {Host = "https://locations-starter-reverse-proxytest.pgsdemo.com/"}

  [[redirects]]
  from = "/assets/static/*"
  to = "https://locations-starter-reverse-proxytest.pgsdemo.com/assets/static/:splat"
  status = 200
  force = true
  headers = {Host = "https://locations-starter-reverse-proxytest.pgsdemo.com/"}

